## Import Packages

In [1]:
import pandas as pd

## Load Data

In [2]:
# Load ADP data
HittersADP = pd.read_csv("AverageDraftPositionData/AverageDraftPositionDataClean/HittersADP2026Clean.csv")
PitchersADP = pd.read_csv("AverageDraftPositionData/AverageDraftPositionDataClean/PitchersADP2026Clean.csv")

# Load with latin1 to safely read the special characters
HittersProj = pd.read_csv("ProjectedDataRAW/HittersProj2026RAW.csv", encoding="utf-8")
PitchersProj = pd.read_csv("ProjectedDataRAW/PitchersProj2026RAW.csv", encoding="utf-8")

In [3]:
# Display top elements of dataframe
HittersProj.head()

,Player Name,Team,Hits (H),Runs Scored (R),Total Bases (TB),Runs Batted In (RBI),Walks (BB),Intentional Walks (IBB),Strikeouts (K),Stolen Bases (SB)
0,Aaron Judge,NYY,149,106,325,120,108,18,162,8
1,Bobby Witt Jr.,KCR,175,104,315,97,48,5,112,37
2,Shohei Ohtani,LAD,160,122,341,119,91,14,157,26
3,Cal Raleigh,SEA,121,82,262,103,74,7,172,7
4,Juan Soto,NYM,148,107,287,100,121,9,123,17

In [4]:
# Display top elements of dataframe
PitchersProj.head()

,Player Name,Team,Innings Pitched (IP),Hits Allowed (H),Earned Runs (ER),Walks Issued (BB),Strikeouts (K),Saves (SV),Blown Saves (BS),Holds (HD)
0,Tarik Skubal,DET,188.0,144,57,38,228,0,0,0
1,Paul Skenes,PIT,184.1,143,56,46,221,0,0,0
2,Garrett Crochet,BOS,180.1,144,61,47,221,0,1,0
3,Logan Webb,SFG,192.2,182,71,44,183,0,0,0
4,Cristopher Sánchez,PHI,185.0,166,66,46,180,0,0,0

## Clean Data

#### Remove Accent Marks

In [5]:
# This automatically turns "Acuña" into "Acuna" and "José" into "Jose"
HittersProj['Player Name'] = HittersProj['Player Name'].str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')
PitchersProj['Player Name'] = PitchersProj['Player Name'].str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')

print("Accent marks successfully removed!")

Accent marks successfully removed!

#### Normalize Team Abbreviations

In [6]:
TeamNames = {
    'ARI': 'Arizona Diamondbacks', 'ATL': 'Atlanta Braves', 'BAL': 'Baltimore Orioles',
    'BOS': 'Boston Red Sox', 'CHC': 'Chicago Cubs', 'CHW': 'Chicago White Sox', 'CWS': 'Chicago White Sox',
    'CIN': 'Cincinnati Reds', 'CLE': 'Cleveland Guardians', 'COL': 'Colorado Rockies',
    'DET': 'Detroit Tigers', 'HOU': 'Houston Astros', 'KCR': 'Kansas City Royals', 'KC': 'Kansas City Royals',
    'LAA': 'Los Angeles Angels', 'LAD': 'Los Angeles Dodgers', 'MIA': 'Miami Marlins',
    'MIL': 'Milwaukee Brewers', 'MIN': 'Minnesota Twins', 'NYM': 'New York Mets',
    'NYY': 'New York Yankees', 'ATH': 'Athletics', 'OAK': 'Athletics', 'PHI': 'Philadelphia Phillies', 
    'PIT': 'Pittsburgh Pirates', 'SDP': 'San Diego Padres', 'SD': 'San Diego Padres',
    'SEA': 'Seattle Mariners', 'SFG': 'San Francisco Giants', 'SF': 'San Francisco Giants', 'STL': 'St. Louis Cardinals',
    'TBR': 'Tampa Bay Rays', 'TB': 'Tampa Bay Rays', 'TEX': 'Texas Rangers', 'TOR': 'Toronto Blue Jays',
    'WSN': 'Washington Nationals', 'WAS': 'Washington Nationals', 'WSH': 'Washington Nationals'
}

# Translate the abbreviations into full names
HittersProj['Team'] = HittersProj['Team'].map(TeamNames).fillna('Free Agent')
PitchersProj['Team'] = PitchersProj['Team'].map(TeamNames).fillna('Free Agent')

In [7]:
# Display top elements of dataframe
HittersProj.head()

,Player Name,Team,Hits (H),Runs Scored (R),Total Bases (TB),Runs Batted In (RBI),Walks (BB),Intentional Walks (IBB),Strikeouts (K),Stolen Bases (SB)
0,Aaron Judge,New York Yankees,149,106,325,120,108,18,162,8
1,Bobby Witt Jr.,Kansas City Royals,175,104,315,97,48,5,112,37
2,Shohei Ohtani,Los Angeles Dodgers,160,122,341,119,91,14,157,26
3,Cal Raleigh,Seattle Mariners,121,82,262,103,74,7,172,7
4,Juan Soto,New York Mets,148,107,287,100,121,9,123,17

In [8]:
# Display top elements of dataframe
PitchersProj.head()

,Player Name,Team,Innings Pitched (IP),Hits Allowed (H),Earned Runs (ER),Walks Issued (BB),Strikeouts (K),Saves (SV),Blown Saves (BS),Holds (HD)
0,Tarik Skubal,Detroit Tigers,188.0,144,57,38,228,0,0,0
1,Paul Skenes,Pittsburgh Pirates,184.1,143,56,46,221,0,0,0
2,Garrett Crochet,Boston Red Sox,180.1,144,61,47,221,0,1,0
3,Logan Webb,San Francisco Giants,192.2,182,71,44,183,0,0,0
4,Cristopher Sanchez,Philadelphia Phillies,185.0,166,66,46,180,0,0,0

In [9]:
# Join projection stats with ADP data; 'inner' keeps only players found in both datasets.
Hitters = pd.merge(HittersProj, HittersADP, on=['Player Name', 'Team'], how='inner')

# Order column variables
HittersOrder = ['Player Name', 'Position', 'Team', 'Hits (H)', 'Runs Scored (R)', 'Total Bases (TB)', 'Runs Batted In (RBI)', 'Walks (BB)',
                'Intentional Walks (IBB)', 'Strikeouts (K)', 'Stolen Bases (SB)',	'ADP']
Hitters = Hitters[HittersOrder]

# Join projection stats with ADP data; 'inner' keeps only players found in both datasets.
Pitchers = pd.merge(PitchersProj, PitchersADP, on=['Player Name', 'Team'], how='inner')

# Order column variables
PitchersOrder = ['Player Name', 'Position', 'Team', 'Innings Pitched (IP)',	'Hits Allowed (H)',	'Earned Runs (ER)',	'Walks Issued (BB)', 
                 'Strikeouts (K)', 'Saves (SV)', 'Blown Saves (BS)', 'Holds (HD)', 'ADP']
Pitchers = Pitchers[PitchersOrder]

In [10]:
# Display top elements of dataframe
Hitters.head()

,Player Name,Position,Team,Hits (H),Runs Scored (R),Total Bases (TB),Runs Batted In (RBI),Walks (BB),Intentional Walks (IBB),Strikeouts (K),Stolen Bases (SB),ADP
0,Aaron Judge,OF,New York Yankees,149,106,325,120,108,18,162,8,1.83
1,Bobby Witt Jr.,SS,Kansas City Royals,175,104,315,97,48,5,112,37,4.00
2,Shohei Ohtani,DH,Los Angeles Dodgers,160,122,341,119,91,14,157,26,1.17
3,Cal Raleigh,C,Seattle Mariners,121,82,262,103,74,7,172,7,13.83
4,Juan Soto,OF,New York Mets,148,107,287,100,121,9,123,17,3.50

In [11]:
# Display top elements of dataframe
Pitchers.head()

,Player Name,Position,Team,Innings Pitched (IP),Hits Allowed (H),Earned Runs (ER),Walks Issued (BB),Strikeouts (K),Saves (SV),Blown Saves (BS),Holds (HD),ADP
0,Tarik Skubal,SP,Detroit Tigers,188.0,144,57,38,228,0,0,0,6.00
1,Paul Skenes,SP,Pittsburgh Pirates,184.1,143,56,46,221,0,0,0,8.50
2,Garrett Crochet,SP,Boston Red Sox,180.1,144,61,47,221,0,1,0,11.33
3,Logan Webb,SP,San Francisco Giants,192.2,182,71,44,183,0,0,0,43.17
4,Cristopher Sanchez,SP,Philadelphia Phillies,185.0,166,66,46,180,0,0,0,26.33

## Create CSV

In [12]:
Hitters.to_csv("ProjectedDataClean/HittersProj2026Clean.csv", index=False)
Pitchers.to_csv("ProjectedDataClean/PitchersProj2026Clean.csv", index=False)

print("\nSaved as 'HittersProj2026Clean.csv' and 'PitchersProj2026Clean.csv'.")

Saved as 'HittersProj2026Clean.csv' and 'PitchersProj2026Clean.csv'.